### PR TITLE
Add storage

### PR DESCRIPTION
**Pull request by Eldonratzlaff**
Preserve data in the browser.

### CODE REVIEW

**Review by roshan-bajgain — COMMENTED** [review]
Hi @Eldonratzlaff, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you have done alone but this is pair programming please do it with your partner

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Eldonratzlaff** [comment]
Hello
My first coding partner left the group on Tuesday and my other partner didn't show up since Wednesday so I'm working alone. I wrote to microverse and still have no response.

**Comment by roshan-bajgain** [comment]
Hello @Eldonratzlaff, bad to hear that but Until you didn't attach the message screenshot from Microverse we cannot do anything I am sorry.

**Review by roshan-bajgain — COMMENTED** [review]
Hi @Eldonratzlaff, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you have done alone but this is pair programming please do it with your partner

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Eldonratzlaff** [comment]
I sent an email to microverse again and I have had no response.

**Review by emmiiorji — COMMENTED** [review]
Hi @Eldonratzlaff, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Invalid2

You have submitted a pair programming project where your partner's commits are missing. Sorry about the issues you have with contacting your partner. Unfortunately, I can't go ahead to review your project as this is a policy. Think about it, since the system still has your partner attached to you, approving your project will allow them to pass the milestone without making any contributions.

If you think your case is special, I would recommend that you request a second opinion using this [form](https://airtable.com/shrQAqnBwek5a0O0s).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Eldonratzlaff** [comment]
Screenshot from 2023-01-08 00-28-13
Please I need this last review to pass. I already tried to contact microverse and I have had no response. I need this review and the last word will be with the microverse when they answer.

**Comment by roshan-bajgain** [comment]
Hello @Eldonratzlaff, I think the microverse team will understand your issue and I thought you don't have to repeat the week.

**Comment by Eldonratzlaff** [comment]
Hello
Would you be so kind as to review my code to find out if there is anything
else I should change so that I can then wait for the decision that
microverse makes. I am more concerned about whether my code works than what
microverse decides.

**Review by KayLemba — APPROVED** [review]
[# STATUS: APPROVED :green_circle: :clap: 

Hello  @Eldonratzlaff          , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Descriptive P.R







 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]

**Pull request merged**
